# the git URL to create the secret for
url: ""

# the git user name used to clone the git URL if its not embedded in the URL
username: ""

# the git password used to clone the git URL if its not embedded in the URL
password: ""

# the git setup commands to configure git to deal with things like insecure registries etc
gitInitCommands: "echo 'no custom git initialisation scripts'"

rbac:
  # if enabled lets install a ClusterRole and ClusterRoleBinding otherwise use Role / RoleBinding
  cluster: true

  # if strict mode lets not assume cluster-admin
  strict: false

image:
  repository: ghcr.io/jenkins-x/jx-git-operator
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "jx-git-operator"
  # a map of annotations to add to the ServiceAccount
  annotations: {}

# define environment variables here as a map of key: value
env:
  # how frequently to poll git
  POLL_DURATION: "20s"

  # the namespace polled for `Secret` resources
  #NAMESPACE: "jx-custom-namespace"

  # the branch to poll. If not specified defaults to the default branch from the clone
  #BRANCH: main

  # disable the applying of resources in a git repository at `.jx/git-operator/resources/*.yaml`. Helpful if switched from ClusterRoles to Roles.
  #NO_RESOURCE_APPLY: true

  # name of the git binary; defaults to `git`
  #GIT_BINARY: git

  # disable the polling loop so that a single poll is performed only
  #NO_LOOP: true

  # the work directory. If not specified a temporary directory is created on startup.
  #WORK_DIR: ...

# define environment variables from here as a map of key: value
envFrom:
- secretRef:
    name: jx-boot-job-env-vars
    optional: true


# a map of annotations to add to the pod
podAnnotations: {}

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi

terminationGracePeriodSeconds: 30

bootServiceAccount:
  enabled: false
  annotations: {}

# a list of ociRegistry credentials for use by helmfile where name is the registry name referenced by helmfile
# ociRegistries:
# - name: jxdev
#   username: regusername
#   password: regpassword
ociRegistries: []

# additional secret keys to place in to a secret optionally mounted by the boot jobs as env vars
# jxBootSecrets:
#   secretKey: secretValue
jxBootJobEnvVarSecrets: {}

# optional list of image pull secrets to use to pull images
jx:
  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: false
